 # Configuration file for Muro build monitoring tool
 -
   servertype: Go
   url: http://pablo.local:8153/go/cctray.xml
   username: 
   password: 
   pipelines:
     -
       name: "Test :: defaultStage"